
DROP TABLE notes;
DROP TABLE todolist;
DROP TABLE calender;
DROP TABLE users;


CREATE TABLE users (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE notes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW(),
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (name) REFERENCES users(name)
);

CREATE TABLE todolist (
    id INT PRIMARY KEY AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW(),
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (name) REFERENCES users(name)
);

CREATE TABLE calender (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    start VARCHAR(255) NOT NULL,
    end VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (name) REFERENCES users(name)
)
